#ifndef KAFFPA_CONFIG_RYEEZ6WJ
#define KAFFPA_CONFIG_RYEEZ6WJ

#define KAHIP_VERSION_MAJOR @KAHIP_VERSION_MAJOR@

#define KAHIP_VERSION_MINOR @KAHIP_VERSION_MINOR@

#define KAHIP_VERSION_PATCH @KAHIP_VERSION_PATCH@

#define KAHIP_VERSION "@KAHIP_VERSION@"

#define KAHIP_EDGE_SIZE @KAHIP_EDGE_SIZE@

#endif /* end of include guard: KAFFPA_CONFIG_RYEEZ6WJ */
