# The main SConscript for the interface.
#

Import('env')

# Build a library from the code in lib/.
libkaffpa_files = [   '..//lib/data_structure/graph_hierarchy.cpp',
                      '..//lib/algorithms/strongly_connected_components.cpp',
                      '..//lib/algorithms/topological_sort.cpp',
                      '..//lib/algorithms/push_relabel.cpp',
                      '..//lib/io/graph_io.cpp',
                      '..//lib/tools/quality_metrics.cpp',
                      '..//lib/tools/random_functions.cpp',
                      '..//lib/tools/graph_extractor.cpp',
                      '..//lib/tools/misc.cpp',
                      '..//lib/tools/partition_snapshooter.cpp',
                      '..//lib/partition/graph_partitioner.cpp',
                      '..//lib/partition/w_cycles/wcycle_partitioner.cpp',
                      '..//lib/partition/coarsening/coarsening.cpp',
                      '..//lib/partition/coarsening/contraction.cpp',
                      '..//lib/partition/coarsening/edge_rating/edge_ratings.cpp',
                      '..//lib/partition/coarsening/clustering/node_ordering.cpp',
                      '..//lib/partition/coarsening/clustering/size_constraint_label_propagation.cpp',
                      '..//lib/partition/coarsening/matching/matching.cpp',
                      '..//lib/partition/coarsening/matching/random_matching.cpp',
                      '..//lib/partition/coarsening/matching/gpa/path.cpp',
                      '..//lib/partition/coarsening/matching/gpa/gpa_matching.cpp',
                      '..//lib/partition/coarsening/matching/gpa/path_set.cpp',
                      '..//lib/partition/initial_partitioning/initial_partitioning.cpp',
                      '..//lib/partition/initial_partitioning/initial_partitioner.cpp',
                      '..//lib/partition/initial_partitioning/initial_partition_bipartition.cpp',
                      '..//lib/partition/initial_partitioning/initial_refinement/initial_refinement.cpp',
                      '..//lib/partition/initial_partitioning/bipartition.cpp',
                      '..//lib/partition/initial_partitioning/initial_node_separator.cpp',
                      '..//lib/partition/uncoarsening/uncoarsening.cpp',
                      '..//lib/partition/uncoarsening/separator/vertex_separator_algorithm.cpp',
                      '..//lib/partition/uncoarsening/separator/vertex_separator_flow_solver.cpp',
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/greedy_neg_cycle.cpp',
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/problem_factory.cpp',
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/augmented_Qgraph.cpp',
                      '..//lib/partition/uncoarsening/refinement/refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/mixed_refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/2way_fm_refinement/two_way_fm.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/flow_refinement/two_way_flow_refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/flow_refinement/boundary_bfs.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/flow_refinement/most_balanced_minimum_cuts/most_balanced_minimum_cuts.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/flow_refinement/flow_solving_kernel/cut_flow_problem_solver.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/quotient_graph_refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/complete_boundary.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/partial_boundary.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/quotient_graph_scheduling/quotient_graph_scheduling.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/quotient_graph_scheduling/simple_quotient_graph_scheduler.cpp',
                      '..//lib/partition/uncoarsening/refinement/quotient_graph_refinement/quotient_graph_scheduling/active_block_quotient_graph_scheduler.cpp',
                      '..//lib/partition/uncoarsening/refinement/kway_graph_refinement/kway_graph_refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/kway_graph_refinement/kway_graph_refinement_core.cpp',
                      '..//lib/partition/uncoarsening/refinement/label_propagation_refinement/label_propagation_refinement.cpp',
                      '..//lib/partition/uncoarsening/refinement/kway_graph_refinement/kway_graph_refinement_commons.cpp',
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/augmented_Qgraph_fabric.cpp', 
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/advanced_models.cpp', 
                      '..//lib/partition/uncoarsening/refinement/kway_graph_refinement/multitry_kway_fm.cpp', 
                      '..//lib/algorithms/cycle_search.cpp',
                      '..//lib/partition/uncoarsening/separator/area_bfs.cpp',
                      '..//lib/partition/uncoarsening/separator/vertex_separator_algorithm.cpp',
                      '..//lib/partition/uncoarsening/separator/vertex_separator_flow_solver.cpp',
                      '..//lib/partition/uncoarsening/refinement/node_separators/fm_ns_local_search.cpp', 
                      '..//lib/partition/uncoarsening/refinement/node_separators/localized_fm_ns_local_search.cpp', 
                      '..//lib/partition/uncoarsening/refinement/cycle_improvements/cycle_refinement.cpp'
                      #'..//lib/parallel_mh/galinier_combine/gal_combine.cpp',
                      #'..//lib/parallel_mh/galinier_combine/construct_partition.cpp',
                      #'..//lib/parallel_mh/parallel_mh_async.cpp',
                      #'..//lib/parallel_mh/population.cpp',
                      #'..//lib/parallel_mh/exchange/exchanger.cpp',
                      #'..//lib/partition/uncoarsening/refinement/tabu_search/tabu_search.cpp'
                      ]

env.Append(LIBPATH=['./optimized'])
env.Append(LIBPATH=['./debug'])
env.Append(LIBPATH=['../interface/'])

env.Library('libkahip', ['kaHIP_interface.cpp']+libkaffpa_files, LIBS=['gomp'])

