name: Windows CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    continue-on-error: true
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DNOMPI=On
    - name: Build
      run: cmake --build build --config Release
    - name: Test interface
      run: |
        cd build/Release
        .\interface_test.exe
